# Generated by Django 3.2.12 on 2024-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20240303_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='link',
            field=models.URLField(),
        ),
    ]
