# Generated by Django 3.2.12 on 2024-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240324_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='sizes',
            field=models.ManyToManyField(to='store.Sizes'),
        ),
    ]
