# Generated by Django 3.2.12 on 2024-04-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_comments_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='product',
        ),
    ]
